spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager-material
    username: root
    password: 0945057018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

